In [8]:
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import pickle
import pandas as pd
import numpy as np
import os

In [12]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,f1_score

def resultados(y_true,y_pred):
    print("Matriz de confusion:")
    matrix = confusion_matrix(y_true, y_pred)
    print(matrix)
    accuracy=accuracy_score(y_true, y_pred)
    precision=precision_score(y_true, y_pred, average='macro')
    recall=recall_score(y_true, y_pred, average='macro')
    f1=f1_score(y_true, y_pred, average='macro')
    print('Precisión(Accuracy): {}'.format(accuracy))
    print('Exactitud(Precisión): {}'.format(precision))
    print('Exhaustividad(Recall): {}'.format(recall))
    print('F1: {}'.format(f1))

In [13]:
iris = load_iris()

In [14]:
X_train, X_test, y_train, y_test = train_test_split(iris.data[:,0:4], iris.target, random_state = 3,test_size=0.1)

In [15]:
svm_classifier = SVC(gamma='auto').fit(X_train, y_train)
y_train_svm = svm_classifier.predict(X_train)
y_pred_svm = svm_classifier.predict(X_test)
print("---Resultados conjunto de entrenamiento")
resultados(y_train,y_train_svm)
print("---Resultados conjunto de test")
resultados(y_test,y_pred_svm)

---Resultados conjunto de entrenamiento
Matriz de confusion:
[[43  0  0]
 [ 0 43  2]
 [ 0  0 47]]
Precisión(Accuracy): 0.9851851851851852
Exactitud(Precisión): 0.9863945578231292
Exhaustividad(Recall): 0.9851851851851853
F1: 0.985479797979798
---Resultados conjunto de test
Matriz de confusion:
[[7 0 0]
 [0 5 0]
 [0 0 3]]
Precisión(Accuracy): 1.0
Exactitud(Precisión): 1.0
Exhaustividad(Recall): 1.0
F1: 1.0


In [ ]:
print("Se procede a entrenar el modelo con todo el conjunto de datos")

In [18]:
data = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                    columns= ['sepal_length', 'sepal_width','petal_length','petal_width','Tarjet'])

In [19]:
svm_classifier = SVC(gamma='auto').fit(data.loc[:, data.columns != 'Tarjet'],data['Tarjet'])

In [22]:
path = "models/"
filename = 'svm_classifier.sav'

In [23]:
try:
    if not os.path.exists('models'):
        os.makedirs('models')
    pickle.dump(svm_classifier, open(path+filename, 'wb'))
    print("Modelo serializado en {}".format(path+filename))
except:
    print("Error al serializar")

Modelo serializado en models/svm_classifier.sav
